### ISSUE TITLE
invalid project file prohibits compilation

### ISSUE THREAD

**Issue by bcartwri96** [AdaCore/gprbuild#73] opened 2019-08-31 02:50 UTC
Hi there. I'm new here, and while I've been programming in Ada for a couple of years, I don't know how it's compiled etc.

Installing on a new MBP running MacOS Mojave (if it's relevant - though I don't think it should be - I'm using ZSH as my shell), with a freshly installed GNAT / GPS env and SPARK too, I get the following error while trying to compile a file:

```
using project file valid_file_here.gpr
No valid configuration found
Generation of configuration files failed
GNAT-TEMP-000001.TMP:1:01: "project" expected
gprbuild: processing of configuration project "/private/var/folders/ym/rp9y64qs6gj1f59rvm7szcxh0000gn/T/GNAT-TEMP-000001.TMP" failed
```

I've tried reinstalling, deleting the file in question and I've scanned the web for helpful hints, yet none have been helpful.
I've also tried issues in gps and another AdaCore repo, but to no avail (mostly because I was unsure where to post this very issue!)

Can someone please help me? Many thanks :)

**Comment by t-14** [comment] 2019-09-02 09:47
This is a duplicate of #70. To reiterate, this project is not the right place to report issues with GNAT Community.

**Closed by t-14** 2019-09-02 09:47 UTC
